STORIES = {
    1: {
        "title": "Jungle Adventure",
        "template": "I walk through the color jungle. I take out my {adjective_one} canteen. There's a {adjective_two} parrot with a {adjective_three} {noun_one} in his mouth right there in front of me in the {adjective_four} trees! I gaze at his {adjective_five} {noun_two}. A sudden sound awakes me from my daydream! A panther’s {verb_one} in front of my head! I {verb_two} his {adjective_six} breath. I remember I have a packet of {noun_three} that makes go into a deep slumber! I {verb_three} it away from me in front of the {noun_four}. Yes he's eating it! I {verb_four} away through the {adjective_seven} jungle. I meet my parents at the tent. Phew! It’s been an exciting day in the jungle.",
        "word_types": [
            "adjective_one",
            "adjective_two",
            "adjective_three",
            "noun_one",
            "adjective_four",
            "adjective_five",
            "noun_two",
            "verb_one",
            "verb_two",
            "adjective_six",
            "noun_three",
            "verb_three",
            "noun_four",
            "verb_four",
            "adjective_seven",
        ],
    },
    2: {
        "title": "Day at the Zoo",
        "template": "Today I went to the zoo. I saw a {adjective_one} {noun_one} jumping up and down in its tree. He {verb_one} through the large tunnel that led to its {adjective_two} {noun_two}. I got some peanuts and passed them through the cage to a gigantic gray {noun_three} towering above my head. Feeding that animal made me hungry. I went to get a {adjective_three} scoop of ice cream. It filled my stomach. Afterwards I had to {verb_two} to catch our bus. When I got home I {verb_three} my mom for a {adjective_four} day at the zoo.",
        "word_types": [
            "adjective_one",
            "noun_one",
            "verb_one",
            "adjective_two",
            "noun_two",
            "noun_three",
            "adjective_three",
            "verb_two",
            "verb_three",
            "adjective_four",
        ],
    },
    3: {
        "title": "A Royal Dream",
        "template": "Last night, I dreamed I was a {noun_one} in a {adjective_one} kingdom. I had a {adjective_two} crown on my head and a {adjective_three} cape around my shoulders. My best friend was a {noun_two} named {name_one}, and we went on an adventure to find a {adjective_four} treasure. Along the way, we had to {verb_one} across a {adjective_five} river and climb a {adjective_six} mountain. Finally, we found the treasure chest, which was filled with {adjective_seven} {noun_three}s. We were so {emotion_one}!",
        "word_types": [
            "noun_one",
            "adjective_one",
            "adjective_two",
            "adjective_three",
            "noun_two",
            "name_one",
            "adjective_four",
            "verb_one",
            "adjective_five",
            "adjective_six",
            "adjective_seven",
            "noun_three",
            "emotion_one",
        ],
    },
    4: {
        "title": "Space Voyage",
        "template": "In the future, people will travel to {place_one} in {adjective_one} spaceships. Each spaceship will have a {adjective_two} {noun_one} that can {verb_one} at the speed of light. On this journey, travelers will meet {adjective_three} aliens with {adjective_four} {body_part_one}s and communicate using {adjective_five} {noun_two}s. The most exciting part of the trip will be when they {verb_two} on the {adjective_six} planet of {planet_name_one}, which is known for its {adjective_seven} {noun_three}s.",
        "word_types": [
            "place_one",
            "adjective_one",
            "adjective_two",
            "noun_one",
            "verb_one",
            "adjective_three",
            "adjective_four",
            "body_part_one",
            "adjective_five",
            "noun_two",
            "verb_two",
            "adjective_six",
            "planet_name_one",
            "adjective_seven",
            "noun_three",
        ],
    },
    5: {
        "title": "Village Discovery",
        "template": "Once upon a time in a {adjective_one} village, there was a {noun_one} named {name_one}. Every day, {name_one} would {verb_one} to the {noun_two} to collect {adjective_two} {noun_three}s. One day, {name_one} found a {adjective_three} {noun_four} that could {verb_two}. Excited, {name_one} took it home and showed it to the {adjective_four} villagers. The {noun_five} became famous, and the village was never the same again.",
        "word_types": [
            "adjective_one",
            "noun_one",
            "name_one",
            "verb_one",
            "noun_two",
            "adjective_two",
            "noun_three",
            "adjective_three",
            "noun_four",
            "verb_two",
            "adjective_four",
            "noun_five",
        ],
    },
    6: {
        "title": "Mystery Mansion",
        "template": "It was a dark and {adjective_one} night when I entered the {adjective_two} mansion. The door creaked as I {verb_one} it open. Inside, I found a {adjective_three} {noun_one} that glowed eerily. Suddenly, a {noun_two} appeared out of nowhere and {verb_two} me. I ran as fast as I could, but the {adjective_four} {noun_three} followed me. Just as I thought it was over, I stumbled upon a hidden {noun_four} that led to a {adjective_five} escape route. I {verb_three} through it and found myself outside, safe and sound.",
        "word_types": [
            "adjective_one",
            "adjective_two",
            "verb_one",
            "adjective_three",
            "noun_one",
            "noun_two",
            "verb_two",
            "adjective_four",
            "noun_three",
            "noun_four",
            "adjective_five",
            "verb_three",
        ],
    },
    7: {
        "title": "Beach Day",
        "template": "We spent a {adjective_one} day at the beach. The sun was shining and the {noun_one} was perfect for {verb_one} in the waves. We built a {adjective_two} sandcastle with {noun_two} towers and {verb_two} it with seashells. Later, we had a picnic with {adjective_three} sandwiches and {noun_three} juice. As the sun set, we collected {adjective_four} {noun_four}s and watched the {noun_five} disappear below the horizon.",
        "word_types": [
            "adjective_one",
            "noun_one",
            "verb_one",
            "adjective_two",
            "noun_two",
            "verb_two",
            "adjective_three",
            "noun_three",
            "adjective_four",
            "noun_four",
            "noun_five",
        ],
    },
    8: {
        "title": "Superhero Adventures",
        "template": "In the city of {place_one}, a {adjective_one} superhero named {name_one} was always ready to {verb_one} danger. One day, a {adjective_two} villain with a {adjective_three} {noun_one} planned to {verb_two} the city. But {name_one} used their {adjective_four} powers to {verb_three} the villain and save the {noun_two}. The citizens of {place_one} cheered and celebrated their hero with a {adjective_five} parade.",
        "word_types": [
            "place_one",
            "adjective_one",
            "name_one",
            "verb_one",
            "adjective_two",
            "adjective_three",
            "noun_one",
            "verb_two",
            "adjective_four",
            "verb_three",
            "noun_two",
            "adjective_five",
        ],
    },
    9: {
        "title": "Fairy Tale Forest",
        "template": "Deep in the {adjective_one} forest, there lived a {noun_one} named {name_one}. {name_one} had a {adjective_two} friend, a talking {noun_two}, who loved to {verb_one}. One day, they discovered a {adjective_three} {noun_three} that granted wishes. They wished for {adjective_four} {noun_four}s and {verb_two} happily ever after in their {adjective_five} home.",
        "word_types": [
            "adjective_one",
            "noun_one",
            "name_one",
            "adjective_two",
            "noun_two",
            "verb_one",
            "adjective_three",
            "noun_three",
            "adjective_four",
            "noun_four",
            "verb_two",
            "adjective_five",
        ],
    },
    10: {
        "title": "School Adventure",
        "template": "At school, my favorite subject is {noun_one}. My teacher, {name_one}, is very {adjective_one} and makes learning fun. Today, we {verb_one} a {adjective_two} experiment that involved {noun_two}s and {adjective_three} reactions. After class, I {verb_two} with my friends in the {noun_three}. It was a {adjective_four} day!",
        "word_types": [
            "noun_one",
            "name_one",
            "adjective_one",
            "verb_one",
            "adjective_two",
            "noun_two",
            "adjective_three",
            "verb_two",
            "noun_three",
            "adjective_four",
        ],
    },
    11: {
        "title": "The Haunted House",
        "template": "On Halloween night, we decided to explore the {adjective_one} haunted house at the end of the street. The {adjective_two} door creaked as we {verb_one} it open. Inside, we found {adjective_three} cobwebs and {adjective_four} shadows dancing on the walls. Suddenly, a {noun_one} appeared and {verb_two} right in front of us. We {verb_three} down the {adjective_five} hallway, our hearts pounding. Each room we entered was more {adjective_six} than the last, with {noun_two}s and {noun_three}s that seemed to {verb_four} at us. In the attic, we discovered a {adjective_seven} {noun_four} that held an old {noun_five}. We opened it cautiously, revealing a {adjective_eight} diary filled with secrets of the past. Just as we were about to leave, the {adjective_nine} {noun_six} started to {verb_five}, sending us running out of the house, vowing never to return.",
        "word_types": [
            "adjective_one",
            "adjective_two",
            "verb_one",
            "adjective_three",
            "adjective_four",
            "noun_one",
            "verb_two",
            "verb_three",
            "adjective_five",
            "adjective_six",
            "noun_two",
            "noun_three",
            "verb_four",
            "adjective_seven",
            "noun_four",
            "noun_five",
            "adjective_eight",
            "adjective_nine",
            "noun_six",
            "verb_five",
        ],
    },
    12: {
        "title": "The Time Machine",
        "template": "I built a {adjective_one} time machine in my garage. It was made of {adjective_two} {noun_one}s and {noun_two}s. I set the date to the year {number_one} and pressed the {adjective_three} button. Suddenly, I was in a {adjective_four} world where dinosaurs {verb_one}. I saw a {adjective_five} T-Rex {verb_two} in the distance. I quickly {verb_three} behind a {noun_three} and watched in awe. After a while, I decided to explore further. I came across a {adjective_six} {noun_four} that looked like a {noun_five}. Inside, I found {adjective_seven} {noun_six} and a map. Following the map, I discovered an ancient {noun_seven} that could {verb_four}. Before returning to my own time, I took a {adjective_eight} {noun_eight} as a souvenir. Back in my garage, I realized I had just experienced the adventure of a lifetime.",
        "word_types": [
            "adjective_one",
            "adjective_two",
            "noun_one",
            "noun_two",
            "number_one",
            "adjective_three",
            "adjective_four",
            "verb_one",
            "adjective_five",
            "verb_two",
            "verb_three",
            "noun_three",
            "adjective_six",
            "noun_four",
            "noun_five",
            "adjective_seven",
            "noun_six",
            "noun_seven",
            "verb_four",
            "adjective_eight",
            "noun_eight",
        ],
    },
    13: {
        "title": "The Lost Treasure",
        "template": "Our journey to find the lost treasure began on a {adjective_one} morning. The map led us through {adjective_two} jungles and across {adjective_three} deserts. Along the way, we encountered {noun_one}s and {noun_two}s that tried to {verb_one} us. But we pressed on, driven by the promise of {adjective_four} riches. On the {adjective_five} day, we reached the hidden temple. Its {adjective_six} walls were covered in ancient {noun_three}s. Inside, we found a {adjective_seven} chamber filled with {adjective_eight} {noun_four}s. At the center was the treasure chest, which opened to reveal {adjective_nine} gems and {noun_five}s. We had done it! The {adjective_ten} treasure was ours, and we celebrated our {adjective_eleven} success.",
        "word_types": [
            "adjective_one",
            "adjective_two",
            "adjective_three",
            "noun_one",
            "noun_two",
            "verb_one",
            "adjective_four",
            "adjective_five",
            "adjective_six",
            "noun_three",
            "adjective_seven",
            "adjective_eight",
            "noun_four",
            "adjective_nine",
            "noun_five",
            "adjective_ten",
            "adjective_eleven",
        ],
    },
    14: {
        "title": "The Magic Forest",
        "template": "One day, I stumbled upon a {adjective_one} forest. The trees were {adjective_two} and the air was filled with the scent of {noun_one}s. As I ventured deeper, I encountered {adjective_three} creatures that could {verb_one} and {verb_two}. They guided me to a {adjective_four} clearing where a {noun_two} stood. The {noun_two} was {adjective_five} and glowed with {adjective_six} light. Inside, I found a {adjective_seven} book that contained {adjective_eight} spells. I read aloud a spell and suddenly, I could {verb_three} like the creatures. I spent the rest of the day exploring the {adjective_nine} forest, discovering {adjective_ten} plants and {adjective_eleven} animals. As the sun set, I returned home, promising to come back and explore the magic forest again.",
        "word_types": [
            "adjective_one",
            "adjective_two",
            "noun_one",
            "adjective_three",
            "verb_one",
            "verb_two",
            "adjective_four",
            "noun_two",
            "adjective_five",
            "adjective_six",
            "adjective_seven",
            "adjective_eight",
            "verb_three",
            "adjective_nine",
            "adjective_ten",
            "adjective_eleven",
        ],
    },
    15: {
        "title": "The Secret Garden",
        "template": "I discovered a {adjective_one} key in my attic. It led me to a {adjective_two} garden hidden behind my house. The garden was filled with {adjective_three} flowers and {adjective_four} plants. In the center was a {adjective_five} fountain surrounded by {noun_one}s. As I explored, I found a {adjective_six} {noun_two} that could {verb_one}. I spent hours in the garden, uncovering its {adjective_seven} secrets. I found {noun_three}s that could {verb_two} and {noun_four}s that could {verb_three}. The garden was a place of {adjective_eight} and wonder. I promised to keep the garden a secret and visit it whenever I needed a {adjective_nine} escape.",
        "word_types": [
            "adjective_one",
            "adjective_two",
            "adjective_three",
            "adjective_four",
            "adjective_five",
            "noun_one",
            "adjective_six",
            "noun_two",
            "verb_one",
            "adjective_seven",
            "noun_three",
            "verb_two",
            "noun_four",
            "verb_three",
            "adjective_eight",
            "adjective_nine",
        ],
    },
}
