MAX_ATTEMPTS = 10
WORDS = [
    'python', 'java', 'kotlin', 'javascript',
    'successful', 'programming', 'language',
    'hangman', 'developer', 'reverse', 'engineer',
    'software', 'testing', 'debugging', 'stack',
    'overflow', 'array', 'list', 'function', 'method',
    'variable', 'constant', 'argument', 'parameter',
    'return', 'break', 'continue', 'loop', 'conditional',
    'statement', 'expression', 'assignment', 'comparison',
    'operator', 'bitwise', 'logical', 'arithmetic', 'shift',
    'bit', 'byte', 'integer', 'float', 'double', 'string',
    'character', 'boolean', 'null', 'arraylist', 'hashmap',
    'queue', 'stack', 'linkedlist', 'tree', 'graph', 'heap',
    'priority', 'search', 'sort', 'insertion', 'bubble',
    'selection', 'quick', 'merge', 'heap', 'radix', 'bucket',
    'counting', 'binary', 'linear', 'exponential', 'recursive',
    'iterative', 'binarysearch', 'bubblesort', 'selectionsort',
    'insertionsort', 'quicksort', 'mergesort', 'heapsort',
    'radixsort', 'bucketsort', 'countingsort', 'graphsearch',
]
